### ISSUE TITLE
Access to Grammar test / NewsQA and complete experimental results

### ISSUE THREAD

**Issue by hwijeen** [YangLinyi/GLUE-X#2]
Hi,
Thanks for the great work! I hope this becomes a widely used benchmark.

I noticed that Grammar test and News QA are not available in the huggingface datasets library and the linked google drive. Where can I find those two datasets?

Additionally, can you share the complete experimental results? Table 4 is very useful but it would be more informative if you could also break it down into per-task accuracy (e.g. performance of SST model evaluated on each of the {Amazon, IMDB, YELP}).

Thanks in advance.

**Comment by YangLinyi** [comment]
Hi Hwijeen,

Thanks for letting me know your questions.

In terms of the dataset, you can find it under the ood_dataset/datasets_self_collected/ path as shown below:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/22150858/221754248-409e597a-690a-4fee-8dbe-9defc3e19ff7.png">

In terms of the experimental results, we will upload the latest results when our submission has been accepted due to the anonymity policy. Hope it can help your research a bit.

Best regards,
Linyi
